# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 22- FoursquareClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Parse'

  # Pods for Project 22- FoursquareClone

end
